### ISSUE TITLE
Public app requires RStudio Connect license

### ISSUE THREAD

**Issue by alievakrash** [ncats/public_sequin#2]
Hello,

I am trying to test the web version of Sequin, but it seems to require RStudio Connect to be installed, and it seems to be specific for Linux and also have several requirements for installation. Is there an easy way to get the public app to work without going on Linux? I am trying to set it up for people who do not necessarly use Linux or computing at all.

Thanks!

Maria

**Comment by cemalley** [comment]
Hi Maria, thanks for letting us know. The public site is up again and does not require local installation: https://sequin.ncats.io/app/
